package day40_exception.recap;

public class FouthTry2 {
    public static void main(String[] args) throws InterruptedException {
        // Compile time exception
        // Options to handle:
        // Option 1: You handle it with try catch -- caught it
        // Option 2: ByPassing it (Ignoring it) Declare it on method signature
        Thread.sleep(1000);
    }
}
